### ISSUE TITLE
User text/question should be sent via a POST http call and appended to the request body (not as a GET request)

### ISSUE THREAD

**Issue by danmo** [gcc3/simple-ai-chat#417]
Sometimes the query string can't take the size of the request. POST request should be used instead.

**Comment by lhypds** [comment]
Hi, @danmo 
Sorry for the late reply; I've been quite busy recently.

Generally, we suggest users use the UI interface rather than the API. But for developers who want to make API calls, we have two options available:

A. /api/generate_sse
Since this uses SSE (Server-Side Events), the current JavaScript API (EventSource function) only supports GET requests, so it can only use query parameters as input. SSE is meant for streaming output, so by default, we use `generate_sse`.

B. /api/generate
This one uses a POST request, but it will only respond when the response text is fully generated. New features will first be supported by `generate_sse`, and some features (like tool calls) are not yet supported by `generate` (work in progress).

Most modern browsers allow longer URLs, so the query parameter should be long enough for text input in most cases. If you face some limit issue, it may not be because the query parameter is too long; it could be that the OpenAI API input limit has been exceeded. (Working on it.)

Tips
1. For longer input you can also consider upload a `.txt` file.
2. Use `role` to reduce some input may also help.

**Comment by lhypds** [comment]
Added the API referance in the documentation.
