### ISSUE TITLE
Better to have previous executed command 

### ISSUE THREAD

**Issue by juyel0516** [gcc3/simple-ai-chat#456]
Once execute a command unable to see that again using the keyboard's up and down keys. It will be better when the keyboard up and down keys are pressed will shows the previous executed command and next executed command.

**Comment by lhypds** [comment]
Good suggestion.
I had considered this before, as we want to provide user a terminal-like experience.

Currently, I am planning to use the up arrow and down arrow keys to navigate between sessions, since the left arrow and right arrow keys are already used to navigate between logs. This feature is under implementation. It will be available soon. Thank you.

**Comment by lhypds** [comment]
@juyel0516 
Done
